[package]
name = "mailboar"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
structopt = { version = "0.3", default-features = false }
env_logger = { version = "0.9", default-features = false }
log = "0.4"
tiny-mailcatcher = "0.9.3"
warp = { version = "0.3", features = ["compression"] }
askama = { version = "0.10", features = ["with-warp", "mime", "mime_guess"] }
askama_warp = "0.11.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1"
