[package]
name = "mailboar"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["io-util", "io-std", "macros", "net", "rt-multi-thread"] }
structopt = { version = "0.3", default-features = false }
env_logger = { version = "0.9", default-features = false }
log = "0.4"
tiny-mailcatcher = "0.9.1"